### PR TITLE
UI bug while updating the max consecutive auto reply field is not showing the existing value

### LINKED ISSUE #631: UI Bug: While updating the "Max Consecutive Auto Reply" field is not showing the existing value

### PR DESCRIPTION
**Pull request by harishmohanraj**
Fixes #631

### CODE REVIEW

File: app/src/client/components/buildPage/PropertySchemaParser.ts [hunk 1]
```diff
@@ -219,7 +224,11 @@ export class PropertySchemaParser implements PropertySchemaParserInterface {
   }
 
   private getNonDropdownDefaultValue(key: string, property: any): any {
-    return this.activeModelObj?.json_str?.[key] ?? property.default ?? '';
+    if (this.activeModelObj) {
+      return this.activeModelObj?.json_str?.[key] ?? '';
```
Comment (davorinrusevljan) [inline app/src/client/components/buildPage/PropertySchemaParser.ts:228]: I am not sure first question mark (`this.activeModelObj?.`) is necessary because `if` now checks if t`his.activeModelObj?` is nullish.

File: app/src/client/components/buildPage/PropertySchemaParser.ts [hunk 2]
```diff
@@ -219,7 +224,11 @@ export class PropertySchemaParser implements PropertySchemaParserInterface {
...
+    } else {
+      return property.default !== undefined ? property.default : '';
```
Comment (davorinrusevljan) [inline app/src/client/components/buildPage/PropertySchemaParser.ts:230]: are we sure property.default is not null?

File: app/src/client/components/buildPage/PropertySchemaParser.ts [hunk 3]
```diff
@@ -108,8 +108,9 @@ export class PropertySchemaParser implements PropertySchemaParserInterface {
     if ('json_schema' in schema) {
       Object.entries(schema.json_schema.properties).forEach(([key, property]: [string, any]) => {
         const isReferenceField = this.checkIfRefField(property);
-        if (isReferenceField) {
-          this.handleReferenceField(key, property, defaultValues);
+        const refTypes = this.getRefTypes(property);
+        if (isReferenceField && refTypes.length > 0) {
```
Comment (davorinrusevljan) [inline app/src/client/components/buildPage/PropertySchemaParser.ts:112]: Is it normal situation to have referenceField that has no refTypes?

What I wanted to is to ask, is it normal, or check for length possibly covers mistake somewhere else?

File: app/src/client/components/buildPage/PropertySchemaParser.ts (hunk 2 above)
Comment (davorinrusevljan) [reply app/src/client/components/buildPage/PropertySchemaParser.ts:230]: ok, it can be null, but it is expected behaviour to return null in that case

File: app/src/client/components/buildPage/PropertySchemaParser.ts (hunk 3 above)
Comment (harishmohanraj) [reply app/src/client/components/buildPage/PropertySchemaParser.ts:112]: Actually no, all the reference fields should have at-least one refTypes. As discussed, I will update the logic in checkIfRefField method to return True only if the field has any reference.

File: app/src/client/components/buildPage/PropertySchemaParser.ts (hunk 1 above)
Comment (harishmohanraj) [reply app/src/client/components/buildPage/PropertySchemaParser.ts:228]: Yup, the first question mark is not needed in this case.

**Review by davorinrusevljan — APPROVED** [review]
